version: '2.1'

services:

    pg12:
      # jdbc:postgresql://localhost:54333/guest
      container_name: pg12
      ports:
      - "54333:5432"
      image: postgres:12-alpine
      env_file: .env
      healthcheck:
        test: "exit 0"
